_target_: midi_xai.models.classic_model.ClassicModel

model:
  _target_: sklearn.neighbors.KNeighborsClassifier
  n_neighbors: 7

imputer:
  _target_: sklearn.impute.SimpleImputer
  strategy: median

scaler:
  _target_: sklearn.preprocessing.RobustScaler

is_transform: True